name: Build and Deploy NodeJS Docker Image

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Bring code from repo into container
        uses: actions/checkout@v2
      - name: Add nodejs and npm to $PATH
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Clean install dependencies
        run: npm ci
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Image and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/board:${{ github.event.release.tag_name }}